export { WorkOrdersComponent } from '@modules/work-orders/pages/work-orders/work-orders.component'
export { WorkOrderComponent } from '@modules/work-orders/pages/work-order/work-order.component'
export { NewWorkOrderComponent } from '@modules/work-orders/pages/new-work-order/new-work-order.component'
export { WorkOrdersService } from '@modules/work-orders/services/work-orders.service'
export { WorkOrdersRoutingModule } from '@modules/work-orders/work-orders.routing.module'
export { WorkOrdersModule } from '@modules/work-orders/work-orders.module'
export { WorkOrderInterface, EmptyWorkOrder } from '@modules/work-orders/interfaces/work-order.interface'
export { ClientDataTabComponent } from '@modules/work-orders/components/client-data-tab/client-data-tab.component'
export { WorkOrderTabComponent } from '@modules/work-orders/components/work-order-tab/work-order-tab.component'
export { mapLanguage } from '@modules/work-orders/shared/mapDatePickerLanguage'