export interface WorkOrderInterface{
    emp: string,
    OR: string,
    fecdoc: Date,
    almnro: string,
    cli: number,
    cif: string,
    nom: string,
    raz: string,
    pju: string,
    dir: string,
    pob: string,
    pobdes: string,
    pro: string,
    prodes: string,
    tel: string,
    email: string,
    tiprep: string,
    maquina: string,
    refer: string,
    numser: string,
    presupuesto: string,
    fecace: Date,
    fecprev: Date,
    fecrep: Date,
    sintoma: Date,
    reparacion: string,
    mec: number,
    km: number,
    tcl: string,
    acti: string,
    pgm: string,
    pgd: string,
    dpp: string,
    rfi: string,
    perfac: number,
    iva: string,
    ivac: boolean,
    req: boolean,
    div: string,
    tar: string,
    com: string,
    codpos: string,
    totimp: number,
    totlbru: number,
    totldto: number,
    totlnet: number,
    totcdpp: number,
    totcrfi: number,
    totcbas: number,
    totciva: number
}

/** Para inicializaciones y por si no queremos rellenar todos los campos desde el CRUD */
export const EmptyWorkOrder = {
    emp: '',
    OR: '',
    fecdoc: new Date(),
    almnro: '',
    cli: 0,
    cif: '',
    nom: '',
    raz: '',
    pju: '',
    dir: '',
    pob: '',
    pobdes: '',
    pro: '',
    prodes: '',
    tel: '',
    email: '',
    tiprep: '',
    maquina: '',
    refer: '',
    numser: '',
    presupuesto: '',
    fecace: new Date(),
    fecprev: new Date(),
    fecrep: new Date(),
    sintoma: new Date(),
    reparacion: '',
    mec: 0,
    km: 0,
    tcl: '',
    acti: '',
    pgm: '',
    pgd: '',
    dpp: '',
    rfi: '',
    perfac: 0,
    ivac: false,
    iva: '',
    req: false,
    div: '',
    tar: '',
    com: '',
    codpos: '',
    totimp: 0,
    totlbru: 0,
    totldto: 0,
    totlnet: 0,
    totcdpp: 0,
    totcrfi: 0,
    totcbas: 0,
    totciva: 0
}